Implement AWS IMDSv2 support
s3fs-fuse/s3fs-fuse pull request #1462
Opened 2020-10-29 23:43 UTC by nmeyerhans

### Relevant Issue (if applicable)
#1445 

### Details

AWS IMDSv2 is a session oriented method for retrieving instance metadata,
including IAM credentials, in Amazon EC2.  It is enabled by default in
non-enforcing mode in AWS (meaning it retains backwards compatibility with
existing IMDSv1 clients), but can be switched to enforcing mode, in which
clients are required to return API tokens with requests.

With this change, we implement support for IMDSv2 and enable it by default when
IAM roles are our source for authentication credentials.  In the event that
s3fs is running in cloud environment offering an IMDSv1-compatible API, we
support graceful fallback to that mode.  It can also be selected explicitly via
the imdsv1only mount option.

More details on IMDSv2 are available at
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
and
https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

2020-10-30 02:49 UTC, nmeyerhans commented
I've revised this PR to avoid using the C++11 `std::to_string` function when converting from an integer value. This should address the earlier test failure.

2020-10-30 12:47 UTC, gaul requested changes
Please address small comments.  Overall this seems fine.

2020-10-30 12:47 UTC, gaul commented on src/curl.cpp
> +		if(S3fsCurl::IAM_api_version > 1){
Fix strange indentation (tabs vs. 4-spaces?)

2020-10-30 12:47 UTC, gaul commented on src/s3fs_help.cpp
> +	"   imdsv1only (default is to use IMDSv2)\n"
Please add to `doc/man/s3fs.1` as well.

2020-10-30 12:47 UTC, gaul commented on src/curl.h
> +		static bool SetIMDSVersion(int version);
Fix indentation.

2020-10-30 12:47 UTC, gaul commented on src/curl.cpp
> +	return true;
Indentation.

2020-11-07 05:48 UTC, merged

2020-11-07 05:49 UTC, gaul commented
Thank you for your contribution @nmeyerhans!