Add AWS SSO authentication and option aws_home_dir (s3fs-fuse#1931)
s3fs-fuse/s3fs-fuse pull request #1932
Opened 2022-04-13 15:51 UTC by VivienMoretto87

This pull request add a new authentication AWS SSO. I have although add the option aws_home_dir to configure the home directory (only available for the authentication AWS SSO)

2022-04-13 15:57 UTC, VivienMoretto87 commented
I have add a new library nlohmann-json. For Ubuntu/Debian it is the package is  nlohmann-json3-dev. Can you tell me how to add into the workflow?

2022-04-14 16:22 UTC, VivienMoretto87 commented
I have pushed all modifications for the ci in the github. All compilations and tests seems to pass

2022-04-17 04:31 UTC, ggtakec commented
@VivienMoretto87 This PR seems to contain some fix.
We are using awscli for testing, but the chnaging to awscli version 2 should be separated from this PR.
I will consider it as well.

2022-04-17 08:03 UTC, VivienMoretto87 commented
@ggtakec Thank you for the reply. Awscli v1 is depretaced and many features are not implemented in awscli 1. 
Aws sso is implemented only in awscli v2 and so I have to use this new version to test it.

2022-04-17 13:16 UTC, ggtakec commented
Prepared PR(#1933) to change AWS CLI version1 to version2.
Try to rebase this PR once it is merged.
I think that it can avoid the part where the error occurs in this PR.

Following is an additional question:
Is it possible to implement without using json parser (nlohmann-json)?
I'm wondering if I should increase the dependencies just to read the config file.
I would also like to hear @gaul opinion.

2022-04-21 13:20 UTC, ggtakec commented
@sqlbot
As you said, I think this is just an additional logic to capture the STS credentials. And this has no way to renew that token.

@VivienMoretto87
Are you thinking of using s3fs from a so-called desktop PC?

I think there is also a way to not incorporate this PR logic directly into the s3fs itself.
After #1927 will be merged, we can delegate the tokens needed by s3 to an external DSO(library).
And I have already created a sample DSO for the authentication logic provided by the AWS SDK.(This includes authentication logic(including STS) provided by the AWS SDK)
It is up to the user to decide whether to use STS, but could you use this instead?

2022-06-19 04:25 UTC, gaul requested changes

2022-06-19 04:25 UTC, gaul commented on src/s3fs_cred.cpp
> +
Remove whitespace changes.  Repeated several times.

2022-06-19 04:25 UTC, gaul commented on src/s3fs_help.cpp
> +    "\n"
Add documentation to `doc/man/s3fs.1`.

2022-06-19 04:25 UTC, gaul commented on test/integration-test-common.sh
> +# Think to add the root certficate of AWS in the file /tmp/keystore.pem to execute aws_cli command
Should this have a `TODO:` prefix?

2022-06-19 04:25 UTC, gaul commented on .github/workflows/ci.yml
> +          PKG_CONFIG_PATH=/usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig ./configure CXXFLAGS='-std=c++11 -DS3FS_PTHREAD_ERRORCHECK=1'
Previously we supported Ubuntu 16.04 and RHEL 6 to a degree #1354 which only supported C++03.  We have talked about C++11 in the context of using the AWS SDK #1068.  I have no objection to this change but want to make sure that it is a conscious one motivated by the json library requirement.

2022-06-19 04:25 UTC, gaul commented on src/s3fs_cred.cpp
> +#define M_ToConstUCharPtr(p)  reinterpret_cast<const unsigned char*>(p)
This macro is unused -- is it necessary?

2022-06-19 04:25 UTC, gaul commented on src/s3fs_cred.cpp
> +    if(sso_start_url != ""){
Change to `!sso_start_url.empty()`.

2022-06-19 04:25 UTC, gaul commented on src/s3fs_cred.cpp
> +        SHA1((unsigned char*)&json_sso_char, strlen(json_sso_char), (unsigned char*)&digest);
Is the `json_sso_char` local necessary?  Can you just call:

```c++
SHA1((unsigned char*)json_sso_string.c_str(), json_sso_string.length(), (unsigned char*)&digest);   
```

2022-06-19 04:25 UTC, gaul commented on src/s3fs_cred.cpp
> +        char mdString[SHA_DIGEST_LENGTH*2+1];
Call `s3fs_hex_lower` instead.

2022-06-19 04:25 UTC, gaul commented on src/s3fs_cred.cpp
> +    // open cerdentials cache pase file
Typo: credentials, parse

2022-06-19 04:25 UTC, gaul commented on src/s3fs_cred.cpp
> +            S3FS_PRN_EXIT("session token is invalid. Think to refresh your sso creedentials.\n Execute aws sso login --profile profile and aws sts get-caller-identity --profile profile");
Typo: credentials

Rephrase as:

```
S3FS_PRN_EXIT("Session token is invalid. Refresh SSO credentials via:\n"
              "aws sso login --profile profile\n"
              "aws sts get-caller-identity --profile profile");
```

2022-06-19 04:25 UTC, gaul commented on src/s3fs_cred.cpp
> +        // Override the aws_home_dir path
Fix indentation.

2022-06-19 04:25 UTC, gaul commented on src/s3fs_cred.cpp
> +            S3FS_PRN_EXIT("Sso configuration is invalid. Think to refresh your sso creedentials.\n Execute aws sso login --profile profile and aws sts get-caller-identity --profile profile");
Use a constant for this repeated string.

2022-06-19 04:25 UTC, gaul commented on src/s3fs_help.cpp
> +    "      - this implementation is only avaialble for sso authentication\n"
Typo: available.

2022-06-19 04:26 UTC, gaul commented
Please resolve merge conflicts as well.

2023-05-14 20:17 UTC, darioackermann commented
We'd love to see this merged. Do you have time to review if we take care of the conflicts?

2023-05-15 11:40 UTC, ggtakec commented
@darioackermann 
Could you try this #1927 merged code(credlib/credlib_ops option) and external DSO library(=https://github.com/ggtakec/s3fs-fuse-awscred-lib)?
This combination(options and libraries) should work for AWS authentication.(but you have to build)

2023-05-15 18:21 UTC, darioackermann commented
> @darioackermann Could you try this #1927 merged code(credlib/credlib_ops option) and external DSO library(=https://github.com/ggtakec/s3fs-fuse-awscred-lib)? This combination(options and libraries) should work for AWS authentication.(but you have to build)

Yes that works, however I'd prefer if this behaviour was avilable as one installable packages, i.e. without manual building steps required. I have worked a bit on the branch and opened #2165 , happy to discuss.

2023-09-16 08:52 UTC, gaul commented
Superseded by #2165.

2023-09-16 08:52 UTC, closed without merging