Added stat information to the mount point
s3fs-fuse/s3fs-fuse pull request #1964
Opened 2022-06-20 17:11 UTC by ggtakec

### Relevant Issue (if applicable)
#1961 #1962

### Details
**NOTE: This fix is a preliminary fix needed to resolve #1961 and #1962.**

This PR allows user to retain the mount point's stat information.

#### Background
The mount point that s3fs mounts does not have stat information.
Therefore, the situation is as follows now:
```
$ stat <mount point>
  File: ‘<mount point>’
  Size: 0               Blocks: 1          IO Block: 4096   directory
Device: 2bh/43d Inode: 1           Links: 1
Access: (0777/drwxrwxrwx)  Uid: ( 9999/<user name>)   Gid: (  100/   users)
Access: 1970-01-01 00:00:00.000000000 +0000
Modify: 1970-01-01 00:00:00.000000000 +0000
Change: 1970-01-01 00:00:00.000000000 +0000
 Birth: -
```
The mount point is unixtime(0) for `mtime` / `ctime` / `atime`, and in `0777` as mode, and the `user` / `group` is as same as s3fs process's `uid` / `gid`.
These can be changed with the `mp_umask` option, but it does not retain stat information.

#### Changes
The mount point can be the root of the bucket or a directory under the bucket.

In the case of bucket root, a file(directory object) for stat information is created and stored in the bucket root.
Its path is `/` and the directory object is also `/`.
This matches usually the directory object(`<directory name>/`) that s3fs is currently creating for the directory. (`/` means that the directory name is empty.)
In this case, the directory object will be `/`.

If the directory is under a bucket(ex. `foo`), the stat information will be used the stat information for that directory.
That is, it uses the information in the directory object(`foo/`).

By handling the stat information of the mount point, it has been modified so that operations such as `chmod` / `chown` / `utimens` etc commands can be performed.

When an operation is performed on the mount point via the s3fs process with this modification, the directory object is output/updated and the stat information is saved.

#### Notes
Once this PR is merged, I can post another PR which resolves for #1961 and #1962 issues.

Also, I think we can abolish(or deprecate) the `mp_umask` option.
If users allow it, I'll create a PR to abolish them later.

2022-07-08 12:16 UTC, gaul requested changes

2022-07-09 06:29 UTC, ggtakec commented on src/s3fs.cpp
> +        strpath = "//";         // strpath is "//"
If strpath is set `/.`, s3fs send the request as `HEAD / HTTP / 1.1`, which will receive a 403 error.
By setting `//`, s3fs sends `HEAD // HTTP / 1.1` and gets the information of the `/` object directly under the bucket top.
This is a special case only if the mount point is the bucket top, as mentioned in the comments above.
So it should set strpath to `//`.

2022-07-09 06:32 UTC, ggtakec commented on test/integration-test-main.sh
> +    add_tests test_time_mountpoint
Yes, I think it works fine.

2022-07-09 06:55 UTC, ggtakec commented on test/integration-test-main.sh
> +	sleep 1
This sleep was unnecessary. to correct.

2022-07-09 07:30 UTC, ggtakec commented
@gaul Fixed one line(test/integration-test-main.sh) and rebase, please re-review this.

2022-10-22 02:46 UTC, ggtakec commented
_This PR is already long overdue._

I'm merging this PR to move forward with code updates.
If you have any problem about this, please let me know.

2022-10-22 02:46 UTC, merged

2023-01-06 04:42 UTC, seongwook-git commented
Hi ggtakec.
I using below ubuntu version & s3fs
==============================================
Ubuntu 18.04.6 LTS
Release:	18.04

s3fs version
Amazon Simple Storage Service File System V1.82(commit:unknown) with GnuTLS(gcrypt)
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
===============================================

I have to use Ubuntu 18.04.
So I have to use V1.82 for s3fs.
Regarding this issue, could it be applied to 1.82 version?

2023-01-07 06:13 UTC, ggtakec commented
@seongwook-git 
Even if your v1.82 mounts the bucket which has stat information by this code, I don't think you can reflect it on the mount point.
On Ubuntu 18.04, I think that you will build s3fs yourself, install it and use it, or you'll get a reliable package.

2025-03-29 08:51 UTC, devhaozi commented
@ggtakec Could you please check this PR? It leads to #2246.