Add `GUARDED_BY` to `FdEntity` and fix locking
s3fs-fuse/s3fs-fuse pull request #2490
Opened 2024-07-05 13:40 UTC by gaul

2024-07-05 13:41 UTC, gaul commented
@ggtakec I annotated the most difficult class and found a variety of unlocked field accesses.  At least some of the comments appear to be wrong.  But I think the static lock checker is doing good work!

2024-07-07 13:30 UTC, ggtakec requested changes
It turns out there is a problem with the FdEntity::RowFlushHasLock() method.
Locking fdent_data_lock here seems to lead to a deadlock.

This method may call UploadPendingHasLock(), which may ultimately call RowFlushHasLock() method again.(There is a possibility of reentrancy.)

So that, RowFlushHasLock() method does not perform any locking, so it is necessary to define a method that wraps this method and performs the locking.

@gaul 
Thanks for finding the locking bug.
I've noticed that some additional code causes deadlocks in other places.
I've submitted a PR #2491 that brings that together, but would you be willing to merge that into this one?
(Or, if you're happy with the content of that PR, I'm happy to merge it.)

2024-07-07 13:30 UTC, ggtakec commented on src/fdcache_entity.cpp
> +    const std::lock_guard<std::mutex> lock(fdent_data_lock);
Reentrancy issues were found in FlushHasLock() and RowFlushHasLock(), so locking here is no longer possible.
More details are explained in the full comments of this PR.

2024-07-07 13:30 UTC, ggtakec commented on src/fdcache_entity.cpp
> +    const std::lock_guard<std::mutex> lock(fdent_lock);
This method is called as a callback from PseudoFdInfo::UploadBoundaryLastUntreatedArea().
The FdEntity object passed to PseudoFdInfo::UploadBoundaryLastUntreatedArea() has already performed this locking, so it cannot be locked here.

2024-07-07 13:30 UTC, ggtakec commented on src/fdcache_entity.cpp
> +    const std::lock_guard<std::mutex> lock(fdent_lock);
This method is called as a callback from PseudoFdInfo::UploadBoundaryLastUntreatedArea().
The FdEntity object passed to PseudoFdInfo::UploadBoundaryLastUntreatedArea() has already performed this locking, so it cannot be locked here.

2024-07-07 13:30 UTC, ggtakec commented on src/fdcache_entity.h
> +            const std::lock_guard<std::mutex> lock(fdent_lock);
This fix is ​​fine, but it causes a deadlock in rename_object() by locking fdent_lock here. (A fix to s3fs.cpp is also required.)

2024-07-07 16:48 UTC, gaul commented
Sorry I hadd not run with `ALL_TESTS=1` so I missed some deadlocks.  The latest PR should address the previous issues.

2024-10-16 00:50 UTC, closed without merging